import type { FilterSchema } from '$lib/components/ui/data-grid/index.js';

export const delivery_slip_filter_schema: FilterSchema = [
  {
    key: 'date',
    label: 'Date',
    type: 'date',
    operators: ['eq', 'gt', 'gte', 'lt', 'lte'],
  },
  {
    key: 'party_id',
    label: 'Pick from list',
    type: 'relation',
    operators: ['eq', 'neq', 'is_present', 'is_not_present'],
    group: 'party',
    groupLabel: 'Party',
    loaderKey: 'customer',
  },
  {
    key: 'party.name',
    label: 'Name',
    type: 'string',
    operators: [
      'eq',
      'starts_with',
      'contains',
      'ends_with',
      'is_empty',
      'is_not_empty',
    ],
    group: 'party',
    groupLabel: 'Party',
  },
  {
    key: 'vehicle_id',
    label: 'Pick from list',
    type: 'relation',
    operators: ['eq', 'neq', 'is_present', 'is_not_present'],
    group: 'vehicle',
    groupLabel: 'Vehicle',
    loaderKey: 'vehicle',
  },
  {
    key: 'vehicle.number_plate',
    label: 'Number Plate',
    type: 'string',
    operators: [
      'eq',
      'starts_with',
      'contains',
      'ends_with',
      'is_empty',
      'is_not_empty',
    ],
    group: 'vehicle',
    groupLabel: 'Vehicle',
  },
  {
    key: 'royalty_number',
    label: 'Pitpass',
    type: 'string',
    operators: ['eq', 'starts_with', 'contains', 'ends_with'],
  },
  {
    key: 'royalty_quantity',
    label: 'Ton',
    type: 'number',
    operators: ['eq', 'neq', 'gt', 'gte', 'lt', 'lte'],
  },
  {
    key: 'product_id',
    label: 'Pick from list',
    type: 'relation',
    operators: ['eq', 'neq', 'is_present', 'is_not_present'],
    group: 'product',
    groupLabel: 'Product',
    loaderKey: 'product',
  },
  {
    key: 'product.name',
    label: 'Name',
    type: 'string',
    operators: ['eq', 'starts_with', 'contains', 'ends_with'],
    group: 'product',
    groupLabel: 'Product',
  },
  {
    key: 'product_quantity',
    label: 'Quantity',
    type: 'number',
    operators: ['eq', 'neq', 'gt', 'gte', 'lt', 'lte'],
  },
  {
    key: 'state',
    label: 'State',
    type: 'enum',
    operators: ['eq', 'neq'],
    options: [
      { label: 'Pending', value: 'pending' },
      { label: 'Billed', value: 'billed' },
      { label: 'Discarded', value: 'discarded' },
    ],
  },
  {
    key: 'metadata.remarks',
    label: 'Remarks',
    type: 'string',
    operators: [
      'contains',
      'starts_with',
      'ends_with',
      'eq',
      'is_empty',
      'is_not_empty',
    ],
    group: 'metadata',
    groupLabel: 'Metadata',
    jsonCustomSubField: {
      type: 'string',
      operators: [
        'contains',
        'starts_with',
        'ends_with',
        'eq',
        'is_empty',
        'is_not_empty',
      ],
    },
  },
];
